/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.BLGeneradorCodigos;
import BL.BLGestionarCliente;
import BL.BLGestionarFactura;
import BL.BLGestionarMenu;
import BL.BLGestionarMesa;
import BL.BLGestionarMesero;
import BL.BLGestionarOrden;
import BL.BLValidar;
import CL.Cliente;
import CL.Factura;
import CL.Orden;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public final class RegistroOrden extends javax.swing.JFrame {

    BLGestionarCliente objBLGestionarCliente = new BLGestionarCliente();
    BLGestionarMesero objBLGestionarMesero = new BLGestionarMesero();
    BLGestionarMesa objBLGestionarMesa = new BLGestionarMesa();
    BLGestionarMenu objBLGestionarMenu = new BLGestionarMenu();
    BLValidar objBLValidar = new BLValidar();
    BLGeneradorCodigos objCodigo = new BLGeneradorCodigos();
    BLGestionarOrden objBLGestionarOrden = new BLGestionarOrden();
    BLGestionarFactura objBLGestionarFactura = new BLGestionarFactura();

    /**
     * Creates new form Registro
     */
    public RegistroOrden() {
        initComponents();
        setLocationRelativeTo(this);

        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        btn2.setVisible(false);
        jButton1.setVisible(false);
        codOrden.enable(false);

        CargarMesero();
        CargarMesa();
        Cargarfuerte();
        CargarEntrada();
        Cargarbebida();

    }

    void generadorCodigo() {
        String cOrden = objCodigo.envioCod("co", "orden");
        codOrden.setText(cOrden);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bx1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        bx2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        box3 = new javax.swing.JComboBox<>();
        box4 = new javax.swing.JComboBox<>();
        box5 = new javax.swing.JComboBox<>();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        codOrden = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("cliente");

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        btn1.setText("buscar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("agregar");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        jLabel2.setText("mesero");

        bx1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("mesa");

        bx2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("menu");

        box3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        box4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        box5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt4.setText("0");
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt4KeyTyped(evt);
            }
        });

        txt5.setText("0");
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt5KeyTyped(evt);
            }
        });

        txt6.setText("0");
        txt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt6KeyTyped(evt);
            }
        });

        btn3.setText("Registrar");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("Cancelar orden");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        jLabel6.setText("orden");

        jButton1.setText("Generar factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(codOrden, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt5)
                                .addComponent(box4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box5, 0, 104, Short.MAX_VALUE)
                                    .addComponent(txt6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3)
                    .addComponent(btn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(6, 6, 6))
        );

        jLabel5.setText("REGISTRAR ORDEN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("Salir de la orden");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel5)
                .addGap(135, 427, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn1)
                                .addComponent(btn2)
                                .addComponent(jButton2)))
                        .addGap(4, 4, 4)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        generadorCodigo();//generamos codigo de orden

        //recogemos valores del cliente
        String identidicacion = (String) txt1.getText();
        String nombre = (String) txt2.getText();
        String apellido = (String) txt3.getText();
        //enviamos al objeto cliente
        Cliente objCliente = new Cliente(identidicacion, nombre, apellido);

        int resCliente = objBLGestionarCliente.envioCliente(objCliente);

        if (resCliente == 0) {
            JOptionPane.showMessageDialog(rootPane, "cliente no registrado");
        } else {
            JOptionPane.showMessageDialog(rootPane, "cliente registrado");
            jPanel1.setVisible(true);
            btn2.setVisible(false);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        eliminaOrden(CodOrde);
        generadorCodigo();//generamos codigo de orden

        String cedula = txt1.getText();
        if (!"".equals(cedula)) {
            Cliente datosCliente = objBLGestionarCliente.comprobarExistenciaCliente(cedula);
            if (datosCliente.getIdentificacion() == null) {
                JOptionPane.showMessageDialog(rootPane, "registre usuario");
                btn2.setVisible(true);
            } else {
                txt2.setText(datosCliente.getNombre());
                txt3.setText(datosCliente.getApellido());
                jPanel1.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "ingrese cedula");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    String Cliente;
    String Mesero;
    String Mesa;
    String CodOrde = "";
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        int[] resValida = new int[5]; //arreglo para almacenar resultados de validacion

        //recgemos valores y validamos a que se hayan complentado los datos       
        this.Mesero = (String) bx1.getSelectedItem();
        resValida[0] = objBLValidar.validarSeleccion(Mesero, "Mesero");

        this.Mesa = (String) bx2.getSelectedItem();
        resValida[1] = objBLValidar.validarSeleccion(Mesa, "Mesa");

        String SelePentrada = (String) box3.getSelectedItem();
        resValida[2] = objBLValidar.validarSeleccion(SelePentrada, "Plato de entrada");

        String SelePfuerte = (String) box4.getSelectedItem();
        resValida[3] = objBLValidar.validarSeleccion(SelePfuerte, "Plato fuerte");

        String SeleBebida = (String) box5.getSelectedItem();
        resValida[4] = objBLValidar.validarSeleccion(SeleBebida, "Bebida");

        //se valida el permiso de registro
        int permiso = objBLValidar.validaPermiso(resValida);

        if (permiso == 1) {//si el permiso es 1 se procede al realizar el registro
            //recogemos valores de las cantidades
            String canEntrada = txt4.getText();
            String canFuerte = txt5.getText();
            String cantBebida = txt6.getText();

            if (("0".equals(canEntrada)) || ("0".equals(canFuerte)) || "0".equals(cantBebida)) {//se valida que las cantidades no sean 0
                JOptionPane.showMessageDialog(rootPane, "Ingrese las cantidades del menu ");
            } else {
                //recogemos la cedula del cliente
                this.Cliente = txt1.getText();
                this.CodOrde = codOrden.getText();

                //transformamos a entero las cantidades
                int cEntrada = Integer.parseInt(canEntrada);
                int cFuerte = Integer.parseInt(canFuerte);
                int cBebida = Integer.parseInt(cantBebida);

                //enviamos valores a la clase orden para almacenarlos
                Orden objOrden = new Orden(CodOrde, SelePentrada, SelePfuerte, SeleBebida, cEntrada, cFuerte, cBebida);

                //enviamos a registrar
                int resOrden = objBLGestionarOrden.registrarOrden(objOrden);

                if (resOrden == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Orden Agregada");
                    CargarEntrada();
                    Cargarfuerte();
                    Cargarbebida();
                    jPanel2.setVisible(true);
                    llenarTabla_2();
                    jButton1.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Algunos campos estan incompletos");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        eliminaOrden(CodOrde);
    }//GEN-LAST:event_btn4ActionPerformed

    void eliminaOrden(String codO) {
        if (!"".equals(codO)) {
            //traemos confirmacion de la orden cancelada
            int resp = JOptionPane.showConfirmDialog(null, "En realidad desea eliminar la orden", "Mensaje de Confirmacion", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                int resCanOrde = objBLGestionarOrden.eliminarOrden(codO);
                //validamos si se a eliminado la orden
                if (resCanOrde == 0) {
                    JOptionPane.showMessageDialog(rootPane, "La orden no a sido eliminada");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "La orden eliminada");
                    jButton1.setVisible(false);
                    jPanel2.setVisible(false);
                }
            }
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Factura objFactura = new Factura(Cliente, Mesero, Mesa, CodOrde);
        if (!"".equals(objFactura.getCliente())) {
            int resFact = objBLGestionarFactura.procesarFactura(objFactura);
            if (resFact == 0) {
                JOptionPane.showMessageDialog(rootPane, "Factura no registrada");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Factura registrada");
                JOptionPane.showMessageDialog(rootPane, "Se generara otra factura");
                this.CodOrde = "";//vaciamos codigo de orden
                oculta();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ah!!! ocurido un error intente registrar otra vez");
            eliminaOrden(CodOrde);
            oculta();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9') && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt1KeyTyped

    private void txt4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9') && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt4KeyTyped

    private void txt5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9') && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt5KeyTyped

    private void txt6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt6KeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9') && (caracter != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt6KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SistMesero().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    void oculta() {
        btn2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
    }

    void llenarTabla_2() {
        String codO = codOrden.getText();

        DefaultTableModel model;
        //arreglo con los titulos de la tabla
        String[] titulos = {"Id", "Pedido", "Cant.", "Total"};
        model = new DefaultTableModel(null, titulos);//enviamos el arreglo en el modelo de la tabla

        String[] fila = new String[4];

        //traemos valores a presentar en la tabla
        String[][] valores = objBLGestionarOrden.DatosOrden(codO);

        //agregamos los valores en el arreglo
        for (int i = 0; i < valores.length; i++) {
            fila[0] = (i + 1) + "";
            for (int j = 0; j < 3; j++) {
                fila[j + 1] = valores[i][j];
            }
            model.addRow(fila);
        }
        jTable1.setModel(model); //agregamos valores en la tabla
    }

    void CargarMesero() {
        bx1.removeAllItems();
        bx1.addItem("seleccionar");
        ArrayList<String> nomMeseros = objBLGestionarMesero.obtNomMesero();
        for (String nombre : nomMeseros) {
            bx1.addItem(nombre);
        }
    }

    void CargarMesa() {
        bx2.removeAllItems();
        bx2.addItem("seleccionar");
        ArrayList<String> numMesa = objBLGestionarMesa.obtNumMesa();
        for (String numero : numMesa) {
            bx2.addItem(numero);
        }
    }

    void CargarEntrada() {
        box3.removeAllItems();
        box3.addItem("seleccionar");
        String tipo = "ct1";
        ArrayList<String> pEntrada = objBLGestionarMenu.obtMenu(tipo);
        for (String entrada : pEntrada) {
            box3.addItem(entrada);
        }
    }

    void Cargarfuerte() {
        box4.removeAllItems();
        box4.addItem("seleccionar");
        String tipo = "ct2";
        ArrayList<String> pFuerte = objBLGestionarMenu.obtMenu(tipo);
        for (String fuerte : pFuerte) {
            box4.addItem(fuerte);
        }
    }

    void Cargarbebida() {
        box5.removeAllItems();
        box5.addItem("seleccionar");
        String tipo = "ct3";
        ArrayList<String> pBebida = objBLGestionarMenu.obtMenu(tipo);
        for (String bebida : pBebida) {
            box5.addItem(bebida);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroOrden().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box3;
    private javax.swing.JComboBox<String> box4;
    private javax.swing.JComboBox<String> box5;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JComboBox<String> bx1;
    private javax.swing.JComboBox<String> bx2;
    private javax.swing.JTextField codOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables
}
